version: "3.9"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: user
      PROXY_ADDRESS_FORWARDING: true

TjKtB1DvDpFPKK0BbukazlVYTCaw