version: "3.2"
services:
  oidc-redirect:
    build: .
    user: "node"
    container_name: qr-login
    ports:
      - "127.0.0.1:8083:8080"
    env_file:
      - secrets.env
    environment:
      - FRONTEND_URL: https://ycc-qr-login.kheops.online
      - OIDC_AUTHORITY: https://ycc-login.naturalimage.ch/auth/realms/ycc
      - OIDC_CLIENT_ID: qr_login
      - KEYBOX_OP_NAME: keybox_op
