version: "3.2"
services:
  oidc-redirect:
    build: .
    user: "node"
    container_name: port_website
    ports:
      - "127.0.0.1:8084:8080"
    environment:
      - FRONTEND_URL=https://ycc-port.naturalimage.ch
      - OIDC_AUTHORITY=https://ycc-qr-login.naturalimage.ch/auth/realms/ycc
      - OIDC_CLIENT_ID=website
